function myPipe = hrv_analysis(varargin)

import meegpipe.node.*;
import physioset.event.class_selector;

USE_OGE = true;
DO_REPORT = true;

nodeList = {};

% Data importer
myNode = physioset_import.new('Importer', physioset.import.edfplus);
nodeList = [nodeList {myNode}];

% Generate events marking the boundaries between experimental conditions
myEventGenerator = pupillator.block_events_generator;
myNode = ev_gen.new('EventGenerator', myEventGenerator);
nodeList = [nodeList {myNode}];

% Annotate the ECG lead using the HRV toolkit
mySel = {...
    class_selector('Type', '^dark$', 'Name', 'dark'), ...
    class_selector('Type', '^pre-red$', 'Name', 'pre-red'), ...
    class_selector('Type', '^post-red$', 'Name', 'post-red'), ...
    class_selector('Type', '^post-blue$', 'Name', 'post-blue'), ...
    class_selector('Type', '^red$', 'Name', 'red'), ...
    class_selector('Type', '^blue$', 'Name', 'blue') ...
    };

myNode = ecg_annotate.new(...
    'EventSelector',    mySel, ...
    'VMUrl',            '192.87.10.186');
nodeList = [nodeList {myNode}];


myPipe = pipeline.new(...
    'Name',             'pupillator-hrv', ...
    'NodeList',         nodeList, ...
    'Save',             false, ...
    'OGE',              USE_OGE, ...
    'GenerateReport',   DO_REPORT, ...
    varargin{:});


end